### ISSUE TITLE
Is the directory indexes plugin supported?

### ISSUE THREAD

**Issue by novabyte** [middleman/middleman-asciidoc#38]
I've got the directory indexes plugin enabled within my `config.rb`. How do I generate links in documents which are re-written to the directory_index format?

For example:
```adoc
link:./setup/install{outfilesuffix}[Install]
```
Becomes:
```html
<a href="./setup/install.html">Install</a>
```
Rather than:
```html
<a href="./setup/install/">Install</a>
or
<a href="./setup/install/index.html">Install</a>
```

**Comment by mojavelinux** [comment]
I have a rough draft in this in place. In PR #39, I check if the directory_indexes extension is activated. If so, I set the `relfileprefix` and `relfilesuffix` attributes on the Asciidoctor processor, aligning with how Middleman is configured to build URLs.

There's a catch, though. Asciidoctor core doesn't yet recognize the `relfilesuffix` attribute. That feature still in development. (see https://github.com/asciidoctor/asciidoctor/issues/1273).

Until that issue is resolved, you need to use a workaround inside each AsciiDoc file. Below the AsciiDoc header--and it's very important that it not be *in* the AsciiDoc header, but rather below it--you need to set the `outfilesuffix` attribute to match the `relfilesuffix` attribute, as follows.

```
= Page Title

// ^ the previous blank line is important!
ifdef::relfilesuffix[:outfilesuffix: {relfilesuffix}]
```

What that does is set the `outfilesuffix` inside the AsciiDoc file, but does not affect how the output path is created (since the attribute is set outside the document header).

**Comment by mojavelinux** [comment]
I've noticed when using the local preview server, if you access a page without the trailing slash, then the path to a relative file breaks. It considers it to be one directory above where it actually is. That seems like a bug in the preview server to me.

**Comment by mojavelinux** [comment]
I've documented how this works in the README. See https://github.com/middleman/middleman-asciidoc#linking-between-pages.

We can probably do better, but it's a start that that should help advance our thinking about this.
